#!/bin/bash
if [ "$(uname)" = "Linux" ]
then
  BRAINWALLET_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
else
  BRAINWALLET_DIR="$(dirname "${BASH_SOURCE[0]}")"
fi
/usr/bin/env python3 "$BRAINWALLET_DIR/brainwallet/brainwallet.py" "$@"
